require('config.data_path').setup()

require('plugins.auto-session')
require('config.autocmd')
require('config.globals')
require('config.keymap')
require('config.lsp')
require('plugins.which-key')
require('plugins.roslyn')
require('plugins.kanagawa')
require('plugins.nvim-treesitter')
-- require('plugins.telescope')
require('plugins.snacks')
require('plugins.oil')
require('config.options')
require('plugins.auto-tag')

-- require('plugins.lualine')
require('plugins.statusline')
require('plugins.mini')
require('plugins.yanky')
require('plugins.db')
require('plugins.gitsigns')
require('plugins.global-note')
require('plugins.harpoon')
require('plugins.highlight-colors')
require('plugins.render-markdown')
-- require('plugins.none-ls')
require('plugins.completion')
require('plugins.undotree')
require('plugins.trouble')
require('plugins.chainsaw')
-- require('plugins.typst')
-- require('plugins.dap')
-- require('plugins.netrw')
